// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/luantranminh/team-management-app/models"
)

var (
	lockRepositoryMockCreate  sync.RWMutex
	lockRepositoryMockGetByID sync.RWMutex
)

// RepositoryMock is a mock implementation of Repository.
//
//     func TestSomethingThatUsesRepository(t *testing.T) {
//
//         // make and configure a mocked Repository
//         mockedRepository := &RepositoryMock{
//             CreateFunc: func(ctx context.Context, name string) (*models.Project, error) {
// 	               panic("TODO: mock out the Create method")
//             },
//             GetByIDFunc: func(ctx context.Context, id models.UUID) (*models.Project, []models.Member, error) {
// 	               panic("TODO: mock out the GetByID method")
//             },
//         }
//
//         // TODO: use mockedRepository in code that requires Repository
//         //       and then make assertions.
//
//     }
type RepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, name string) (*models.Project, error)

	// GetByIDFunc mocks the GetByID method.
	GetByIDFunc func(ctx context.Context, id models.UUID) (*models.Project, []models.Member, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// GetByID holds details about calls to the GetByID method.
		GetByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID models.UUID
		}
	}
}

// Create calls CreateFunc.
func (mock *RepositoryMock) Create(ctx context.Context, name string) (*models.Project, error) {
	if mock.CreateFunc == nil {
		panic("RepositoryMock.CreateFunc: method is nil but Repository.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	lockRepositoryMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockRepositoryMockCreate.Unlock()
	return mock.CreateFunc(ctx, name)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedRepository.CreateCalls())
func (mock *RepositoryMock) CreateCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	lockRepositoryMockCreate.RLock()
	calls = mock.calls.Create
	lockRepositoryMockCreate.RUnlock()
	return calls
}

// GetByID calls GetByIDFunc.
func (mock *RepositoryMock) GetByID(ctx context.Context, id models.UUID) (*models.Project, []models.Member, error) {
	if mock.GetByIDFunc == nil {
		panic("RepositoryMock.GetByIDFunc: method is nil but Repository.GetByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  models.UUID
	}{
		Ctx: ctx,
		ID:  id,
	}
	lockRepositoryMockGetByID.Lock()
	mock.calls.GetByID = append(mock.calls.GetByID, callInfo)
	lockRepositoryMockGetByID.Unlock()
	return mock.GetByIDFunc(ctx, id)
}

// GetByIDCalls gets all the calls that were made to GetByID.
// Check the length with:
//     len(mockedRepository.GetByIDCalls())
func (mock *RepositoryMock) GetByIDCalls() []struct {
	Ctx context.Context
	ID  models.UUID
} {
	var calls []struct {
		Ctx context.Context
		ID  models.UUID
	}
	lockRepositoryMockGetByID.RLock()
	calls = mock.calls.GetByID
	lockRepositoryMockGetByID.RUnlock()
	return calls
}
